// generated by genversion
export const version = '0.0.8'

// generated by insert_vars.js script:
export const versionTS = '2022-01-08T16:38:33.994Z'
export const packageName = 'doomd-sk-windi-template'