// generated by genversion
export const version = '0.1.0'

// generated by insert_vars.js script:
export const versionTS = '2022-04-03T02:33:17.213Z'
export const packageName = 'doomd-sk-windi-template'