// generated by genversion
export const version = '0.0.5'

// generated by insert_vars.js script:
export const versionTS = '2021-12-16T21:53:10.899Z'
export const packageName = 'doomd-sk-windi-template'